# Utiliser l'image officielle PHP avec Apache (version 8.2)
FROM php:8.2-apache

# Installer les extensions PHP nécessaires
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copier les fichiers de l'application Laravel dans le conteneur
COPY . /var/www/html

# Changer les permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Activer le module Apache rewrite
RUN a2enmod rewrite

# Configurer Apache pour utiliser le répertoire Laravel
COPY ./laravel.conf /etc/apache2/sites-available/000-default.conf

# Installer les dépendances PHP de Laravel avec Composer
WORKDIR /var/www/html
RUN composer install

# Copier les scripts de création des liens symboliques et d'entrée
COPY creation_liens_symbolique.sh /var/www/html/creation_liens_symbolique.sh
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

# Rendre les scripts exécutables
RUN chmod +x /var/www/html/creation_liens_symbolique.sh \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

# Configurer le script d'entrée personnalisé
ENTRYPOINT ["docker-entrypoint.sh"]

# Configurer les droits pour le répertoire de stockage
RUN chown -R www-data:www-data storage \
    && chmod -R 775 storage 

# Exposer le port 80 pour accéder à l'application
EXPOSE 80