#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

WWWUSER="${WWWUSER:-1000}"
WWWGROUP="${WWWGROUP:-1000}"

if [ -f /var/www/html/package.json ]; then
    mkdir -p /var/www/html/node_modules
    chown -R "$WWWUSER:$WWWGROUP" /var/www/html/node_modules

    if [ ! -d /var/www/html/node_modules/.bin ]; then
        if [ -f /var/www/html/package-lock.json ]; then
            gosu "$WWWUSER" npm ci
        else
            gosu "$WWWUSER" npm install
        fi
    fi
fi

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
