<?php

return [
    'definitions' => [
        'mail.mailer' => [
            'group' => 'Mail',
            'label' => 'Mailer',
            'type' => 'select',
            'env' => 'MAIL_MAILER',
            'fallback' => 'log',
            'config' => 'mail.default',
            'rules' => ['nullable', 'string', 'in:log,smtp,array'],
            'options' => ['log' => 'Log', 'smtp' => 'SMTP', 'array' => 'Array'],
            'description' => 'Transport utilise pour envoyer les emails.',
        ],
        'mail.host' => [
            'group' => 'Mail',
            'label' => 'SMTP host',
            'type' => 'string',
            'env' => 'MAIL_HOST',
            'fallback' => '127.0.0.1',
            'config' => 'mail.mailers.smtp.host',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'mail.port' => [
            'group' => 'Mail',
            'label' => 'SMTP port',
            'type' => 'integer',
            'env' => 'MAIL_PORT',
            'fallback' => 2525,
            'config' => 'mail.mailers.smtp.port',
            'rules' => ['nullable', 'integer', 'min:1', 'max:65535'],
        ],
        'mail.username' => [
            'group' => 'Mail',
            'label' => 'SMTP username',
            'type' => 'string',
            'env' => 'MAIL_USERNAME',
            'config' => 'mail.mailers.smtp.username',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'mail.password' => [
            'group' => 'Mail',
            'label' => 'SMTP password',
            'type' => 'password',
            'env' => 'MAIL_PASSWORD',
            'config' => 'mail.mailers.smtp.password',
            'rules' => ['nullable', 'string', 'max:255'],
            'secret' => true,
        ],
        'mail.from_address' => [
            'group' => 'Mail',
            'label' => 'From email',
            'type' => 'email',
            'env' => 'MAIL_FROM_ADDRESS',
            'fallback' => 'hello@example.com',
            'config' => 'mail.from.address',
            'rules' => ['nullable', 'email', 'max:255'],
        ],
        'mail.from_name' => [
            'group' => 'Mail',
            'label' => 'From name',
            'type' => 'string',
            'env' => 'MAIL_FROM_NAME',
            'config' => 'mail.from.name',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'services.mapbox.token' => [
            'group' => 'API',
            'label' => 'Mapbox token',
            'type' => 'password',
            'env' => 'MAPBOX_TOKEN',
            'config' => 'services.mapbox.token',
            'rules' => ['nullable', 'string', 'max:1000'],
            'secret' => true,
            'description' => 'Utilise pour les suggestions adresse et calculs de trajet.',
        ],
    ],
];
