<?php

$openAiModels = [
    'gpt-5.5' => 'GPT-5.5 - plus capable',
    'gpt-5.4' => 'GPT-5.4 - équilibré qualité/coût',
    'gpt-5.4-mini' => 'GPT-5.4 mini - recommandé coût/latence',
    'gpt-5.4-nano' => 'GPT-5.4 nano - très rapide/économique',
    'gpt-4.1' => 'GPT-4.1 - robuste non-reasoning',
    'gpt-4.1-mini' => 'GPT-4.1 mini - rapide',
    'gpt-4.1-nano' => 'GPT-4.1 nano - économique',
    'gpt-4o' => 'GPT-4o - legacy robuste',
    'gpt-4o-mini' => 'GPT-4o mini - legacy économique',
];

return [
    'definitions' => [
        'mail.mailer' => [
            'group' => 'Mail',
            'label' => 'Mailer',
            'type' => 'select',
            'env' => 'MAIL_MAILER',
            'fallback' => 'log',
            'config' => 'mail.default',
            'rules' => ['nullable', 'string', 'in:log,smtp,array'],
            'options' => ['log' => 'Log', 'smtp' => 'SMTP', 'array' => 'Array'],
            'description' => 'Transport utilise pour envoyér les emails.',
        ],
        'mail.host' => [
            'group' => 'Mail',
            'label' => 'SMTP host',
            'type' => 'string',
            'env' => 'MAIL_HOST',
            'fallback' => '127.0.0.1',
            'config' => 'mail.mailers.smtp.host',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'mail.port' => [
            'group' => 'Mail',
            'label' => 'SMTP port',
            'type' => 'integer',
            'env' => 'MAIL_PORT',
            'fallback' => 2525,
            'config' => 'mail.mailers.smtp.port',
            'rules' => ['nullable', 'integer', 'min:1', 'max:65535'],
        ],
        'mail.username' => [
            'group' => 'Mail',
            'label' => 'SMTP username',
            'type' => 'string',
            'env' => 'MAIL_USERNAME',
            'config' => 'mail.mailers.smtp.username',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'mail.password' => [
            'group' => 'Mail',
            'label' => 'SMTP password',
            'type' => 'password',
            'env' => 'MAIL_PASSWORD',
            'config' => 'mail.mailers.smtp.password',
            'rules' => ['nullable', 'string', 'max:255'],
            'secret' => true,
        ],
        'mail.from_address' => [
            'group' => 'Mail',
            'label' => 'From email',
            'type' => 'email',
            'env' => 'MAIL_FROM_ADDRESS',
            'fallback' => 'hello@example.com',
            'config' => 'mail.from.address',
            'rules' => ['nullable', 'email', 'max:255'],
        ],
        'mail.from_name' => [
            'group' => 'Mail',
            'label' => 'From name',
            'type' => 'string',
            'env' => 'MAIL_FROM_NAME',
            'config' => 'mail.from.name',
            'rules' => ['nullable', 'string', 'max:255'],
        ],
        'services.mapbox.token' => [
            'group' => 'API',
            'label' => 'Mapbox token',
            'type' => 'password',
            'env' => 'MAPBOX_TOKEN',
            'config' => 'services.mapbox.token',
            'rules' => ['nullable', 'string', 'max:1000'],
            'secret' => true,
            'description' => 'Utilisé pour les suggestions adresse et calculs de trajet.',
        ],
        'services.openai.api_key' => [
            'group' => 'API',
            'label' => 'OpenAI API key',
            'type' => 'password',
            'env' => 'OPENAI_API_KEY',
            'config' => 'services.openai.api_key',
            'rules' => ['nullable', 'string', 'max:1000'],
            'secret' => true,
            'description' => 'Utilisee pour normaliser les imports Excel des lots.',
        ],
        'services.openai.model' => [
            'group' => 'API',
            'label' => 'OpenAI model',
            'type' => 'select',
            'env' => 'OPENAI_MODEL',
            'fallback' => 'gpt-4o-mini',
            'config' => 'services.openai.model',
            'rules' => ['nullable', 'string', 'in:'.implode(',', array_keys($openAiModels))],
            'options' => $openAiModels,
            'description' => 'Modele utilise pour la normalisation structuree des fichiers.',
        ],
        'services.openai.timeout' => [
            'group' => 'API',
            'label' => 'OpenAI timeout',
            'type' => 'integer',
            'env' => 'OPENAI_TIMEOUT',
            'fallback' => 75,
            'config' => 'services.openai.timeout',
            'rules' => ['nullable', 'integer', 'min:10', 'max:300'],
            'description' => 'Timeout HTTP par appel OpenAI, en secondes.',
        ],
        'services.openai.connect_timeout' => [
            'group' => 'API',
            'label' => 'OpenAI connect timeout',
            'type' => 'integer',
            'env' => 'OPENAI_CONNECT_TIMEOUT',
            'fallback' => 10,
            'config' => 'services.openai.connect_timeout',
            'rules' => ['nullable', 'integer', 'min:3', 'max:60'],
            'description' => 'Timeout de connexion à OpenAI, en secondes.',
        ],
        'services.openai.import_chunk_size' => [
            'group' => 'API',
            'label' => 'OpenAI lignes par paquet',
            'type' => 'integer',
            'env' => 'OPENAI_IMPORT_CHUNK_SIZE',
            'fallback' => 10,
            'config' => 'services.openai.import_chunk_size',
            'rules' => ['nullable', 'integer', 'min:1', 'max:100'],
            'description' => 'Nombre de lignes Excel envoyées par appel OpenAI pendant un import.',
        ],
        'services.firebase.project_id' => [
            'group' => 'API',
            'label' => 'Firebase project ID',
            'type' => 'string',
            'env' => 'FIREBASE_PROJECT_ID',
            'config' => 'services.firebase.project_id',
            'rules' => ['nullable', 'string', 'max:255'],
            'description' => 'Projet Firebase utilisé pour les notifications push mobiles.',
        ],
        'services.firebase.service_account_path' => [
            'group' => 'API',
            'label' => 'Firebase service account path',
            'type' => 'string',
            'env' => 'FIREBASE_SERVICE_ACCOUNT_PATH',
            'config' => 'services.firebase.service_account_path',
            'rules' => ['nullable', 'string', 'max:500'],
            'description' => 'Chemin serveur vers le JSON service account Firebase Admin.',
        ],
        'services.firebase.service_account_json' => [
            'group' => 'API',
            'label' => 'Firebase service account JSON',
            'type' => 'password',
            'env' => 'FIREBASE_SERVICE_ACCOUNT_JSON',
            'config' => 'services.firebase.service_account_json',
            'rules' => ['nullable', 'string', 'max:10000'],
            'secret' => true,
            'description' => 'Alternative au chemin fichier. À éviter si un fichier sécurisé hors dépôt est possible.',
        ],
    ],
];
